DOESN'T WORK. Updated the XML parser. Merged both the GUI start and the XML: when the program is called using the -xml label followed by the XML file name (i.e. sudo ./RTHybrid -xml file.xml) it doesn't launch the GUI. Multiple definition problem in file_selector_functions.h fixed: if you write 'int var;' in a header file it is being DEFINED, so instead 'extern int var;' should be use so it is only DECLARED and then you define it normally in the corresponding source file. Still failing to compile: rthybrid_xml_main.cpp:15: undefined reference to xml_clamp_parser(char*, clamp_args*)